name: iMC Bans
version: 1.0.1
main: com.skyost.imcbans.Main
author: Skyost
website: http://www.imc-bans.eu/
description: UNE liste DES serveurs
commands:
 imcbdl:
  usage: /imcbdl
  description: Update the database.
  permission: imcbans.player.dllist
 imcbchk:
  usage: /imcchk
  description: Check for updates.
  permission: imcbans.player.checkforupdate
 imcbip:
  usage: /imcbip <player>
  description: Print the IP of <player>.
  permission: imcbans.player.getip
 imcbreason:
  usage: /imcbreason <player>
  description: Ban <player> for <reason>.
  permission: imcbans.player.banplayer
 imcbupdt:
  usage: /imcbupdt
  description: Update the plugin. CONSOLE ONLY !
 imcbver:
  usage: /imcbver
  description: Show your version of iMC Bans.
  permission: imcbans.player.getversion
permissions:
 imcbans.player.dllist:
  default: op
  description: Allow you to update the list.txt file.
 imcbans.player.checkforupdate:
  default: op
  description: Allow you to check for an update of iMC Bans.
 imcbans.player.getversion:
  default: true
  description: Allow you to view the version of iMC Bans.
 imcbans.player.banplayer:
  default: op
  description: Allow you to ban a player with a reason.
 imcbans.player.getip:
  default: op
  description: Allow you to get the IP of a player.
