name: iMC Bans
version: 0.5
main: com.skyost.imcbans.main
author: Skyost
website: http://www.imcbans.cu.cc/
description: UNE liste DES serveurs
commands:
    imcbdl:
        usage: /imcbdl
        description: Retelecharge la base de donnees
    imcbchk:
        usage: /imcchk
        description: Cherche des mises a jours
    imcbip:
        usage: /imcbip <player>
        description: Obtient l'adresse IP de <player>
        
    imcbreason:
        usage: /imcbreason <player>
        description: Ban de <player> avec <reason>
        
    imcbver:
        usage: /imcbver
        description: Montre la version du plugin