name: iMC Bans
version: 0.3
main: com.skyost.imcbans.list
author: Skyost
description: Nothing at this point
commands:
    imcbdl:
        usage: /imcbdl
        description: Retelecharge la base de donnees
    imcbip:
        usage: /imcbip joueur
        description: Obtient l adresse IP de <joueur>
    imcbver:
        usage: /imcbver
        description: Montre la version du plugin